### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by sukyoungjeong-furiosa** [furiosa-ai/furiosa-models#135]
### Dependencies

- [ ] Update release note #138 
- [x] Update model list in README.md #138 
- [ ] #106 
- [ ] #107 
- [ ] Generate artifacts for the target toolchain (0.9.0) and update tests #141 
- [ ] ~Add assertion in examples to clarify the output format (as a label string)~
- [x] Update optimal batch sizes in documentation for new models.
- [x] #139 
- [x] #140

**Comment by hyunsik** [comment]
0.9.0 릴리즈는 이미 완료되었으므로 이슈 닫겠습니다.
