### ISSUE TITLE
[Umbrella Issue] Make furiosa-models deliverable without compiler

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/furiosa-models#7]
Model Zoo 목적에 맞게 필요한 경우 배포 시 컴파일러를 완전 제거 하고 컴파일러가 빠진 Nux 만으로 배포할 수 있도록 다음과 같은 다양한 일을 진행합니다.

- [x] 컴파일된 ENF를 furiosa-models에 추가 및 ENF 파일 및 디렉토리 구조 설계
  * Scope을 최소로 하기 위해 Model zoo에 포함되는 모델은 warboy-2pe 로 컴파일된 ENF로 한정
  * 컴파일러 버전에 따른 ENF 파일을 저장하고 엑세스 할 수 있어야 함
- [x] 단기적으로 현재 시스템에 설치된 모델들을 일괄적으로 컴파일 하여 위에서 설계된 파일 및 디렉토리 구조에 맞게 ENF를 저장하는 Makefile 구현
- [x] libnux 등 런타임 라이브러리가 컴파일러 없이 패키징
- [x] furiosa-models가 컴파일러 버전에 맞게 DVC에서 파일을 엑세스 오도록 개선
